obstacle_range: 6.0
raytrace_range: 8.5
robot_radius: 0.1
footprint_padding: 0.0 
map_topic: /map
subscribe_to_updates: true
global_frame: map
robot_base_frame: agent_base
always_send_full_costmap: true
static_layer:
    map_topic: /map
    subscribe_to_updates: true
plugins:
    - {name: inflation_layer,        type: "costmap_2d::InflationLayer"}
    - {name: voxel_layer,         type: "costmap_2d::VoxelLayer"}

voxel_layer:
  enabled: true
  footprint_clearing_enabled: True
  z_voxels: 16
  unknown_threshold: 0
  mark_threshold: 3
  observation_sources: point_cloud_sensor
  point_cloud_sensor: 
    sensor_frame: agent_sensor
    data_type: PointCloud2
    topic: /sync/localCloud
    marking: true
    clearing: true
    inf_is_valid: false
    obstacle_range: 4.0
    raytrace_range: 4.0
