local_costmap:
  update_frequency: 5
  publish_frequency: 5
  transform_tolerance: 13.0
  static_map: false
  rolling_window: true
  width: 7.5
  height: 7.5
  origin_x: 0
  origin_y: 0
  resolution: 0.1
  inflation_radius: 0.2
  plugins:
      - {name: voxel_layer,         type: "costmap_2d::VoxelLayer"}
      - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
